wind:
  years:
    "2020": { type: "xlsx", url: "https://www.arcgis.com/sharing/rest/content/items/31ef242a23484e79bbb19d6b29203179/data" }
    "2019": { type: "xlsx", url: "https://cctegis.maps.arcgis.com/sharing/rest/content/items/f2adbf257d73429d8ad163b6ec8b40f1/data" }
    "2018": { type: "xlsx", url: "https://cctegis.maps.arcgis.com/sharing/rest/content/items/b1a5746518cc4e848bb810d1df77ee94/data" }
    "2017": { type: "xlsx", url: "https://cctegis.maps.arcgis.com/sharing/rest/content/items/b1817b5a657249c0bdf969d939825407/data" }
    "2016": { type: "xlsx", url: "https://cctegis.maps.arcgis.com/sharing/rest/content/items/7d76f813db154c0d8737631f7240c55f/data" }

air_quality:
  years:
    "2022": { type: "xlsx", url: "https://www.arcgis.com/sharing/rest/content/items/5555f5a529d644e994f6986f9d03af45/data" }
    "2021": { type: "zip", item_page: "https://cctegis.maps.arcgis.com/home/item.html?id=97b0fe851c6f4d86b2492eb09fe42935" }
    "2020": { type: "zip", item_page: "https://cctegis.maps.arcgis.com/home/item.html?id=2fb7a43763704482a244aab9dd6f9ae6" }
    "2019": { type: "zip", item_page: "https://cctegis.maps.arcgis.com/home/item.html?id=c5a3514b193844c5b58347a338ecc811" }
    "2018": { type: "zip", item_page: "https://cctegis.maps.arcgis.com/home/item.html?id=52e908dffce04a7b9e44a9fdc2ec2c1e" }
    "2017": { type: "zip", item_page: "https://cctegis.maps.arcgis.com/home/item.html?id=b9e9a53a20fc43bd81ef3c1e941ed351" }
    "2016": { type: "zip", item_page: "https://cctegis.maps.arcgis.com/home/item.html?id=5ed2613386b040e59b75fc821bbc8d17" }

