# Station mapping with surrogate keys for City of Cape Town environmental monitoring
# This provides consistent station identification across all data sources

wind_stations:
  # Normalised station names (handle variations like "Somerset-West" vs "Somerset West")
  station_mappings:
    - station_pk: 1
      station_code: "ATLAN001"
      station_name: "Atlantis AQM Site"
      normalised_names: ["Atlantis AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Atlantis"

    - station_pk: 2
      station_code: "BELLV001"
      station_name: "Bellville South AQM Site"
      normalised_names: ["Bellville South AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Bellville South"

    - station_pk: 3
      station_code: "BOTHA001"
      station_name: "Bothasig AQM Site"
      normalised_names: ["Bothasig AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Bothasig"

    - station_pk: 4
      station_code: "GOODW001"
      station_name: "Goodwood AQM Station"
      normalised_names: ["Goodwood AQM Station"]
      location_type: "AQM"
      description: "Air Quality Monitoring station in Goodwood"

    - station_pk: 5
      station_code: "KHAYE001"
      station_name: "Khayelitsha AQM Site"
      normalised_names: ["Khayelitsha AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Khayelitsha"

    - station_pk: 6
      station_code: "SOMER001"
      station_name: "Somerset West AQM Site"
      normalised_names: ["Somerset West AQM Site", "Somerset-West AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Somerset West"

    - station_pk: 7
      station_code: "TABLE001"
      station_name: "Tableview AQM Site"
      normalised_names: ["Tableview AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Tableview"

    - station_pk: 8
      station_code: "FORES001"
      station_name: "Foreshore AQM Site"
      normalised_names: ["Foreshore AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Foreshore"

    - station_pk: 9
      station_code: "MOLTE001"
      station_name: "Molteno AQM Site"
      normalised_names: ["Molteno AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Molteno"

    - station_pk: 10
      station_code: "PLATT001"
      station_name: "Plattekloof AQM Site"
      normalised_names: ["Plattekloof AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Plattekloof"

    - station_pk: 11
      station_code: "WALLA001"
      station_name: "Wallacedene AQM Site"
      normalised_names: ["Wallacedene AQM Site"]
      location_type: "AQM"
      description: "Air Quality Monitoring site in Wallacedene"

# Metric definitions for wind data
wind_metrics:
  - metric_code: "wind_direction"
    metric_name: "Wind Direction"
    unit: "degrees"
    description: "Wind direction in degrees (0-360)"
    valid_range: [0, 360]

  - metric_code: "wind_speed"
    metric_name: "Wind Speed"
    unit: "m/s"
    description: "Wind speed in meters per second"
    valid_range: [0, 100]  # Reasonable upper limit for wind speed

# Air quality metrics definitions
air_quality_metrics:
  - metric_code: "no2"
    metric_name: "Nitrogen Dioxide"
    unit: "ug/m3(S)"
    description: "Nitrogen dioxide concentration"
    valid_range: [0, 500]

  - metric_code: "o3"
    metric_name: "Ozone"
    unit: "ug/m3(S)"
    description: "Ground-level ozone concentration"
    valid_range: [0, 400]

  - metric_code: "pm10"
    metric_name: "Particulate Matter 10μm"
    unit: "ug/m3(S)"
    description: "Particulate matter with diameter ≤10 micrometers"
    valid_range: [0, 1000]

  - metric_code: "pm25"
    metric_name: "Particulate Matter 2.5μm"
    unit: "ug/m3(S)"
    description: "Fine particulate matter with diameter ≤2.5 micrometers"
    valid_range: [0, 500]

  - metric_code: "so2"
    metric_name: "Sulfur Dioxide"
    unit: "ug/m3(S)"
    description: "Sulfur dioxide concentration"
    valid_range: [0, 350]

# Data quality flags
quality_flags:
  - flag_code: "VALID"
    description: "Valid measurement"
  - flag_code: "NODATA"
    description: "No data available"
  - flag_code: "INVLD"
    description: "Invalid measurement"
  - flag_code: "SUSPECT"
    description: "Suspect measurement (outside normal range)"
  # Air quality specific flags
  - flag_code: "DOWN"
    description: "Equipment down"
  - flag_code: "SAMP"
    description: "Below sampling limit"
  - flag_code: "RS232"
    description: "Communication error"
  - flag_code: "ZERO"
    description: "Zero reading"
  - flag_code: "CALIB"
    description: "Calibration in progress"